### ISSUE TITLE
Sjekk for virus linker

### ISSUE THREAD

**Issue by Zenjjim** [TIHLDE/shorty#1]
Burde legge inn sjekk for at URLen ikke er "malicious". Dette kan gjøres med f.eks. [VirusTotal](https://developers.virustotal.com/v3.0/reference#overview ) som tilbyr et api for dette.

**Comment by olros** [comment]
Burde ikke dette gjøres ved opprettelse av link, istedenfor når man åpner short-linken? Hvis ikke vil jo lasting av linker gå saktere

**Comment by Zenjjim** [comment]
det er sant, trodde det var her :D
